### ISSUE TITLE
String specification should support list indexes

### ISSUE THREAD

**Issue by Granitosaurus** [mahmoud/glom#102]
Right now it's a bit awkard to select values from objects that are mixed between lists and dicts.

Lets say we have object of this structure

    {'cats':
        [
            {'name': 'mustache'},
            {'name': 'whiskey'}
        ]
    }

If we want to get name of the first cat in current `glom` version we'd have to use a tuple specification with `T` object:

    ('cats', T[0], 'name')

This is awfully complex and ugly for such a simple operation. Would be great if this would be supported:

    cats[0].name

edit: it's actually supported under:

    cats.0.name

**Comment by mahmoud** [comment]
Hi @Granitosaurus! 

I would do it this way:

`res = glom(target, T.cats[0].name)`

The string specification is really just a minor concession to hook people into glom. The goal is to push toward T expressions,  as strings don't scale well (no indenting conventions, syntax highlighting). Hopefully the approach above works for you (it's also faster than the string and tuple ways :) )

**Comment by Granitosaurus** [comment]
@mahmoud that's a really good point! I hadn't though of it this way. I think it would be a great idea to clarify this in the docs and expand a bit on specification. I've went through tutorial pages several times and really only found about `T` in related github issue.

**Comment by mahmoud** [comment]
Oh right, these are dicts not objects, that's my bad. The `T` object is for very explicit access, [`Path()`](https://glom.readthedocs.io/en/latest/api.html#glom.Path) is the one to use for flexible access.

As far as updating the tutorial, that's very true! We should really get `T` and `Path()` better integrated into the tutorial. I'd welcome a PR! Otherwise it'll have to wait (probably a long while) until I have a rainy day.

**Comment by Granitosaurus** [comment]
@mahmoud `Path` is great! Wouldn't it make sense to parse string specifications as paths? 

i.e. `Path('cats', -1, 'name')` could be easily parsed out of `cats[-1].name`. 

I'd like to work on some recipe page when I get the hang of this, been using `glom` a lot since python jq clients ended up being just too slow and awkward to use.

**Comment by mahmoud** [comment]
Yep! If memory serves, strings are just parsed as `Path.from_text()`

**Comment by Granitosaurus** [comment]
I'm closing this issue as string specification does support list indexes, just in an unusual format:

for example: `cats.-1.name` should be used instead of intuative ~~`cats[-1].name`~~
