### ISSUE TITLE
JQ comparison

### ISSUE THREAD

**Issue by AlexandreGalois** [mahmoud/glom#104]
> "The CLI that glom packs is very similar in function to jq, except it uses Python as its query language, instead of making its own."

I tried to reproduce something from jq in glom but I can't seem to manage. This is my starting structure:

`{
    "a": 1,
    "b": [
        {
            "c": 1,
            "d": 5
        },
        {
            "c": 2,
            "d": 9
        }
    ]
}`

And this is the desired result:

`{
  "a": 1,
  "c": 1,
  "d": 5
}
{
  "a": 1,
  "c": 2,
  "d": 9
}
`

With jq I would write `{a} + .b[]` ...but I get stuck trying to write it in glom..Not even sure if this is a good use-case for glom. 

Any pointers are greatly appreciated!

**Comment by kurtbrose** [comment]
oh hey, cool --

so this doesn't quite fit into the current scope of glom in the sense that it is very hard to build dicts with dynamic keys

assuming you know the keys are exactly a, c, d you could do this

```
(Assign(S['a'], T['a']), T['b'], [{'a': S['a'], 'c': 'c', 'd': 'd'}])
```

basically, Assign and S let you put away variables for later, while the glom remains composable

**Comment by kurtbrose** [comment]
we had a new release; added `Let` which simplifies assigning to scope:

```
def test_let():
    data = {'a': 1, 'b': [{'c': 2}, {'c': 3}]}
    output = [{'a': 1, 'c': 2}, {'a': 1, 'c': 3}]
    assert glom(data, (Let(a='a'), ('b', [{'a': S['a'], 'c': 'c'}]))) == output
```

still nowhere near as compact as the jq expression, but improved:
```python
(Assign(S['a'], T['a']), T['b'], [{'a': S['a'], 'c': 'c', 'd': 'd'}])
 (Let(a='a'), 'b', [{'a': S['a'], 'c': 'c'}])
```

**Comment by kurtbrose** [comment]
also added `Invoke`

```python
(Let(a='a'), 'b', [Invoke(dict).specs(a=S['a']).star(kwargs=T)])
```

that lets you achieve the behavior of passing through all keys of the sub dict rather than explicitly enumerating them (cure worse than the disease?  not sure)

**Comment by kurtbrose** [comment]
I think we've juiced this as much as we could for design ideas, I'm going to go ahead and close

thanks for reporting this!
