### ISSUE TITLE
How to access data with "dotted" key values

### ISSUE THREAD

**Issue by davidban77** [mahmoud/glom#105]
Hello, was trying to find some similar issue but couldn't find one, so figured I should just ask :).

I have a quick question. How can I access data where there are some keys in the dictionary that have "." in them. For example:

```
{'vrf': {'default': {'address_family': {'ipv4': {'routes': {'10.0.1.0/24': {'route': '10.0.1.0/24',
       'active': True,
       'ubest': 1,
       'mbest': 0,
```

Trying to access data like:
`glom(p2, 'vrf.default.address_family.ipv4.routes.10.0.1.0/24')`

```python

PathAccessError: could not access '10', part 5 of Path('vrf', 'default', 'address_family', 'ipv4', 'routes', '10', '0', '1', '0/24'), got error: KeyError('10')

```

Thought there was some escape characters that could be used, but did not find any reference on it.

**Comment by mahmoud** [comment]
Hi @davidban77! The `.`-delimited syntax is just a convenient shortcut, so it has its limitations, but of course there are a couple ways to move beyond it!

The closest equivalent to what you want is this:

```python
from glom import glom, Path

glom(p2, Path('vrf', 'default', 'address_family', 'ipv4', 'routes', '10.0.1.0/24'))
```
This is also the route to use if you have non-string keys (e.g., integers) in your structure, as well as the preferred route for programmatic construction of paths. If you need more powers, I recommend looking at [`T`](https://glom.readthedocs.io/en/latest/api.html#object-oriented-access-and-method-calls-with-t) :)
