### ISSUE TITLE
Give value to `__version__` attribute of package

### ISSUE THREAD

**Issue by pablo-esteban** [mahmoud/glom#128]
Hi,

Currently, it is not possible to check the version programmatically:

```
>>> import glom
>>> glom.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'glom' has no attribute '__version__'
```

Tested on glom 19.2.0 and 19.10.0.

**Comment by mahmoud** [comment]
This is available in the just-published v20.7.0. Thanks for the suggestion!
