### ISSUE TITLE
glob/pattern/wildcard support?

### ISSUE THREAD

**Issue by ickc** [mahmoud/glom#133]
Hi,

It seems that currently a wildcard like glob pattern is not supported.

e.g.

```py
eg = {
    'a': {
        'b': '123',
        'c': '456,
    }
}

# expecting something like
glom(eg, 'a.*')
>>> ['123', '456']
```

Basically there's a certain nested level of dict with keys as some yet unknown names and each has some further dict structure. (i.e. spec could be `a.*.c` or something.)

Given the current capability in glom, it seems that if the data is in the following format it fits glom better:

```py

eg = {
    'a': [
        {
            'name': 'b',
            'value: '123',
        },{
            'name': 'c',
            'value: '456',
        }
    ],
}
```

But unfortunately I don't have the control of the data.

Will a feature like this be considered (or if it can already do it with a different syntax)?

Thanks.

**Comment by kurtbrose** [comment]
we're totally working on match mode, which does this and so much more :-)

holding it up is getting good exception stacks, but that is nearly ready

https://github.com/mahmoud/glom/tree/match-mode

**Comment by kurtbrose** [comment]
actually on closer inspection I think you want this -- https://github.com/mahmoud/glom/issues/45

`.*` and `.**` for single level and recursive multi-paths

**Comment by ickc** [comment]
Thanks! Closing this to favor #45.
