### ISSUE TITLE
Referencing the whole target - How to move data one level down into a into a list dictionaries?

### ISSUE THREAD

**Issue by mborus** [mahmoud/glom#139]
Hi, I have a nested structure with some global values and a list of dictionaries.
I'm trying to move all global key/value pairs this nested list.

    target = {'date': '2020-04-01',
     'location': 'A',
     'items': [
         {'name': 'A', 'id': 'A1'},
         {'name': 'B', 'id': 'B1'},
         {'name': 'C', 'id': 'C1'}
    ]}

The required result it

    [{'name': 'A',
      'id': 'A1',
      'data': 'location',
      'date': '2020-01-01',
      'location': 'A'},
     {'name': 'B',
      'id': 'B1',
      'data': 'location',
      'date': '2020-01-01',
      'location': 'A'},
     {'name': 'C',
      'id': 'C1',
      'data': 'location',
      'date': '2020-01-01',
      'location': 'A'}]

I can do list, by adding the target name to the spec

    spec = ('items', [Assign( 'date', target['date'])], [Assign( 'location', target['location'])])
    glom(target, spec)

but that feels like cheating. Is there a way of avoiding the use of the variable _target_ in this spec to get the same result?

**Comment by mahmoud** [comment]
Hmm, I think there's a way to do this with the scope, which I'm only just now realizing is not documented. 

It's hinted at in the [glom function doc](https://glom.readthedocs.io/en/latest/api.html#glom.glom) (it's the last parameter). You can address the scope with `glom.S`, and it has a dict-like interface. 

A common trick is to put a mutable structure in the scope and then modify it, then pull the structure back out. @kurtbrose can probably illustrate. :)

**Comment by mborus** [comment]
Thanks for the reply. I tried with scope yesterday, but couldn't guess the correct syntax.

This is one of the attempts I tried, which all returned a similar result:

    from glom import S, glom, Assign

    target = {'date': '2020-04-01',
     'location': 'A',
     'items': [
         {'name': 'A', 'id': 'A1'},
         {'name': 'B', 'id': 'B1'},
         {'name': 'C', 'id': 'C1'}
    ]}

    spec = Spec(('items', [Assign( 'date', S['date'])], [Assign( 'location', S['location'])]))

    glom(target, spec, scope=target)

Result:

    [{'name': 'A', 'id': 'A1', 'date': S['date'], 'location': S['location']},
     {'name': 'B', 'id': 'B1', 'date': S['date'], 'location': S['location']},
     {'name': 'C', 'id': 'C1', 'date': S['date'], 'location': S['location']}]

Here `S['date']` is of the type `glom.core.TType`

**Comment by kurtbrose** [comment]
this is exactly what the Let spec is for

```python
>>> from glom.core import Let
>>> from glom import S, T, Merge, Fill
>>> spec = (Let(base={'date': 'date', 'location': 'location'}), [Fill([T, S['base']]), Merge()])
>>> glom(target, spec)
[['date', {'date': '2020-04-01', 'location': 'A'}], ['items', {'date': '2020-04-01', 'location': 'A'}], ['location', {'date': '2020-04-01', 'location': 'A'}]]
```

**Comment by kurtbrose** [comment]
would be convenient if there was a version of `Merge()` that merged a sequence of specs so there didn't need to be a separate `Filll()` to build the list first

**Comment by mahmoud** [comment]
Interesting idea. Will give it a think. Also, a bit more info about scope can be found in this WIP doc: https://github.com/mahmoud/glom/blob/master/docs/extensions.rst

**Comment by mborus** [comment]
@kurtbrose: Thanks for the example. I changed it a bit and now get the results I was asking for.

    spec = (Let(base={'date': 'date', 'location': 'location'}), 
            'items', 
             [(Fill([T, S['base']]), Merge())]
           )
    glom(target, spec)

Result

    [{'name': 'A', 'id': 'A1', 'date': '2020-04-01', 'location': 'A'},
     {'name': 'B', 'id': 'B1', 'date': '2020-04-01', 'location': 'A'},
     {'name': 'C', 'id': 'C1', 'date': '2020-04-01', 'location': 'A'}]

**Comment by mahmoud** [comment]
Thinking about doing `Merged.specs(T, S['base'])` as a shorthand for that `Fill` line above. Nice work!

**Comment by mahmoud** [comment]
To clarify, that's not in the API yet, just floating a design idea. :)
