### ISSUE TITLE
runnable spec / equivalent of re.compile for glom-specs

### ISSUE THREAD

**Issue by kurtbrose** [mahmoud/glom#14]
Might be nice to have the equivalent of `re.compile()` or a runnable spec object.

E.g.

```
s = Spec({ glom-spec })
result = s.glom(target)
```

**Comment by mahmoud** [comment]
This is being addressed in #41

**Comment by mahmoud** [comment]
#41 was merged and will be released in 18.1. See the changelog for more info.
