### ISSUE TITLE
rename Literal to Echo?

### ISSUE THREAD

**Issue by kurtbrose** [mahmoud/glom#141]
`Literal` sounds very langauge-design-ey; `Echo` describes more what the spec does

```
Wherever a Literal object is encountered in a spec, it is
    replaced with its wrapped *value* in the output.
```

versus if we called it `Echo`

```
Echo emits the wrapped value as its output.
```

**Comment by kurtbrose** [comment]
also `Echo` is shorter and faster to say :-)

**Comment by kurtbrose** [comment]
huh.... also kind of a neat self-vivifying spec

```python
Invoke(Echo).constants(S[Spec])
```

**Comment by kurtbrose** [comment]
```python
>>> glom(None, Invoke(Literal).specs(S[UP][Spec]))
Literal(Invoke(<class 'glom.core.Literal'>).specs(S[Sentinel('UP')][<class 'glom.core.Spec'>]))
```

**Comment by kurtbrose** [comment]
oh whoops not sure the self-reference cycle works

**Comment by mahmoud** [comment]
Summarizing an outside conversation around this, not sure this rename is enough of a clarity delta for most, especially with the connotations around printing and debugging. I think there's a bigger clarity issue in some places that this rename on its own won't fix.
