### ISSUE TITLE
S.a instead of S['a']

### ISSUE THREAD

**Issue by kurtbrose** [mahmoud/glom#146]
`Let` is turning out to be very useful, figure out some special casing so that `(Let(a=1), S['a'])` can be written as `(Let(a=1), S.a)` for better readability

One way to special case this would be to modify `__getattr__` on `TType`, `if t is S: return t[key]`

**Comment by mahmoud** [comment]
Yeah I'm pretty +1 on this. In fact I thought we talked about it and even made a ticket, if not, thanks for making one!

**Comment by kurtbrose** [comment]
this is done now as part of the variable capture :-)
