### ISSUE TITLE
Extracting items from a list (with a default)

### ISSUE THREAD

**Issue by salvapinyol** [mahmoud/glom#147]
Hi, pretty new on glom but it looks very promising!
I didn't found any support group or slack so I'm raising this issue here for help.

with this target:

target = {
    "pluto": {"moons": 6, "population": None},
    "venus": {"population": {"aliens": 5}},
    "earth": {"moons": 1, "population": {"humans": 7700000000, "aliens": 1}},
}

I need to produce this output:
[('pluto',6), ('venus',0), ('earth',1)]

Being the int the number of moons of the planet, 0 if moons key doesn't exist.

Thanks!

Salva.

**Comment by kurtbrose** [comment]
```python
(T.items(), [Fill(T[0], T[1].get('moons', 0))])
Invoke(zip).specs((T.values(), [T[1].get('moons', 0)]), T.keys()) 
```
hmmm

**Comment by mahmoud** [comment]
Hey Salva! We've got a new release coming this week that adds the `Match` spec that'll give you a better syntax:

```python
>>> glom(target, (Match({str: T.get('moons', 0)}), T.items()))
[('earth', 1), ('venus', 0), ('pluto', 6)]
```

All of these use the [`T`](https://glom.readthedocs.io/en/latest/api.html#object-oriented-access-and-method-calls-with-t) object, which is a really handy thing to learn once you're getting into glom :)

**Comment by salvapinyol** [comment]
> 
> 
> ```python
> (T.items(), [Fill((T[0], T[1].get('moons', 0)))])
> Invoke(zip).specs((T.values(), [T[1].get('moons', 0)]), T.keys()) 
> ```
> 
> hmmm

Thanks @kurtbrose!! , I tried something similar of your first spec but it didn't work:

(T.items(), [Fill((T[0], (T[1], Coalesce("moons", default=0))))])

It seems that Coalesce can't be used there.

Regarding your second spec it doesn't work to me. Maybe you did a typo and the correct spec is this?

Invoke(zip).specs((T.values(), [T.get('moons', 0)]), T.keys()) 

Salva

**Comment by salvapinyol** [comment]
> 
> 
> Hey Salva! We've got a new release coming this week that adds the `Match` spec that'll give you a better syntax:
> 
> ```python
> >>> glom(target, (Match({str: T.get('moons', 0)}), T.items()))
> [('earth', 1), ('venus', 0), ('pluto', 6)]
> ```
> 
> All of these use the [`T`](https://glom.readthedocs.io/en/latest/api.html#object-oriented-access-and-method-calls-with-t) object, which is a really handy thing to learn once you're getting into glom :)

Thanks @mahmoud!! Looking forward for the new release.

Salva
