### ISSUE TITLE
variable capture into scopes

### ISSUE THREAD

**Issue by kurtbrose** [mahmoud/glom#149]
1. `Let()` can assign `Var()` instead of a specific value, means "hold this spot for later"
1. `S.var` before a value is bound raises `GlomError(variable accessed before assignment)` same as python
1. any `Let()` which assigns a concrete value in a child will overwrite
1. `Var(final=True)` if it should have only-once assignment
1. a deeper `Let()` which defines another `Var()` under the same name will override it for child specs, same as normal behavior for variables in the scope (arising very naturally out of implementation)

```python
(
    Let(last=Var()),
    [Let(last=T)],
    S.last
)
# same as
T[-1]
````

Open question -- this means `Let()` from deeper within a spec will "leak up"

Alternative

* `Let()` can assign a `Vars()` into scope
* `Vars()` can be assigned to via normal means

```python
(
    Let(vars=Vars()),
    [assign(S.vars.last)],
    S.vars.last
)
```

this helps by making the assignment more explicit -- however `.vars` doesn't seem like a very useful semantic object, and if everybody uses the same one, we are back to the same problem of deeper nesting overwriting

Alternative 2

explicit separate `LetVar()` which performs indirect assignment

```python
(
    Let(last=Var()),
    [LetVar(last=T)],
    S.last
)
```

This mitigates most of the overwriting problem -- `LetVar()` is presumably not written without intending a `Let()` above it -- and since `Let()` at different levels while define the same variable will mask each other, `LetVar()` and `Let()` will always pair up correctly

Put another way -- a correct spec can be nested in another correct spec without worrying about "crosstalk" between their variables; the only way cross-talk would happen is if the inner spec was incorrect

**Comment by kurtbrose** [comment]
thinking about this some more -- maybe we should have a special accessor for variables -- `S['a']` was always kind of a hack

**Comment by kurtbrose** [comment]
hmmm... I guess the notion of "scope" is dead on for variables though

**Comment by mahmoud** [comment]
Hmm, I see the case that `LetVar()` mitigates, but:

1. Do we really care to be that careful?
2. Will Let() still work with Var(), at the risk of leaking?
3. What if there are two Var() instances with a name collision? Final is based on assignment, not declaration right? Should Let check if a variable is already declared? (Loop back to 1.)

**Comment by kurtbrose** [comment]
There is no problem with redeclare of variables -- the "closer" one is
visible just as with any other variable in the scope.

The problem with Let() pushing data into a parent Let() is fundamental.
Now the behavior of Let() (and potentially the whole spec) depends on the
structure if the parent spec.

This is bad for the same reason that global state is bad.  Now you can't
read a spec and tell what the behavior is.

([Let(a=1)], S.a)

Is that spec correct or will it error?

Depends on if there is a Let(a=Var ()) at a higher level or not.

Here, we can make it ambiguous too:

(Let(a=1), [Let(a=2)], S.a)

Evaluates to 1 normally.  2 if there's a Var() above.

It is really, really bad to have this kind of ambiguity.

**Comment by mahmoud** [comment]
I don't suppose you'd want to let undeclared vars just float all the way to the top of the scope stack?? Hey it seems to have worked out for eichmascript. But tbh we could have a "strict_let" flag in the root scope that changes that behavior, even.

I guess the more strict thing is safer for now. There may be a better syntax or convention later, but this is explicit and strict and works for now. It's not like I'm using Var()-related functionalities daily and LetVar() isn't _that_ clunky.

**Comment by mahmoud** [comment]
- [ ] More testing (referenced before assignment, reassigning to final, and misc)
- [ ] Scope docs (need to add string space)
- [ ] docs for Let / Val / Var / LetVar
- [ ] Literal aliased to Val

Remembering now we had a `V` once upon a time. Maybe there's a future sugaring possible, but not here. Also, not going to do anything about redeclaration right now.

**Comment by kurtbrose** [comment]
interesting -- "hygenic" macros are a language feature for detecting that variable references don't leak across boundaries

if there was a compiler step we could maybe forward detect these kind of things and / or isolate them somehow

**Comment by mahmoud** [comment]
Yeah, there are definitely things to learn in the macro space ([link to hygienic macros](https://en.wikipedia.org/wiki/Hygienic_macro)). Maybe after `*` we can look at glompilation.

**Comment by kurtbrose** [comment]
we just need to come up with a tasteful way to extend the spec API so that a spec can return its children

**Comment by kurtbrose** [comment]
okay, unpacking my previous design it would look something like this:

```python
(
    Let(last=Var()),
    [LetVar(last=T)],
    S.last
)

# compare with

(
    Vars([V.last])
    S.last
)
```

so, `Vars()` defines a variable scope, all variables declared go to the closest enclosing variable scope

**Comment by kurtbrose** [comment]
Another possibility might be to separate `S` from variable access -- we could use `A` for assign and `V` for variable, or `A` for access and `V` for variable?  (My thought is just that `A` looks kind of like an upside down `V` so they make good opposites:

```python


(
    Vars([V.last])
    A.last
)

```

**Comment by kurtbrose** [comment]
maybe to introduce fewer new symbols....

```python
(
    Let(last=default),
    [V.last],
    S.last
)
```

**Comment by kurtbrose** [comment]
we could also define semantics that require a default value in `Let`, and then allow `V.var` to overwrite them  (not sure if this is a good idea or not)

**Comment by kurtbrose** [comment]
we could add markers and pos args to `Let()` to modify behavior

e.g.

`Let(a=FINAL)` -- `a` can be assigned to once

`Let(STRICT)` -- only declared variables can be assigned

**Comment by kurtbrose** [comment]
```python
(
    Let(),
    Match(Or( (0, V.a), {0: V.a})),
    S.a
)
```
that would take `(0, val)` or `{0: val}` and return `val`

**Comment by kurtbrose** [comment]
I think we have a design merged to master I'm going to close this issue since we are past all this design discussion
