### ISSUE TITLE
lack of explicit formatting for lists

### ISSUE THREAD

**Issue by Niccolum** [mahmoud/glom#161]
Good day.

Faced with the fact that I need a filter in the form of user input of strings in order to return the result to the user. I.g. he create the filter in the form of 'foo.bar.baz'

The problem is that in this form it is completely impossible to work with lists, for example, there is no `'foo.*.bar'` for data
`{'foo': [{'bar': 'baz'}, {'bar':'baz'}, {'bar':'baz'}]}`

Also in this case, when the user specs are entered, it is not possible to save the same data structure, namely
`['foo.bar', 'foo.baz']`
With data
`{'foo': {'bar': 1, 'baz': 2, 'x': 3}}`
will return
`1, 2` instead
`{'foo': {'bar': 1, 'baz': 2}}`

I understand that it is possible to make specs with my hands to get what I need, but the catch is in the user input, which does not allow specifying it complicated. Maybe, all the same, how can this be done?

**Comment by kurtbrose** [comment]
we're working on * and ** :-) https://github.com/mahmoud/glom/pull/144

**Comment by Niccolum** [comment]
> we're working on * and ** :-) #144

That's great!

What about second part of issue?
is it possible to see it in near future?)

**Comment by kurtbrose** [comment]
oh sure

```python
data = {'foo': [{'bar': 1}, {'bar': 2}, {'x': 3}]}
glom(data, {'foo': ('foo', [Coalesce({'bar': 'bar'}, default=SKIP)])})
# {'foo': [{'bar': 1}, {'bar': 2}]}
```

does that look like what you are trying to do?

**Comment by kurtbrose** [comment]
We're also working on match mode https://github.com/mahmoud/glom/pull/94 which will give some alternative ways of expressing that kind of thing

```python
glom(data, Match({'foo': Auto([Or({'bar': 'bar'}, default=SKIP)])}))
# {'foo': [{'bar': 1}, {'bar': 2}]}
```

**Comment by Niccolum** [comment]
Yes, of course.
But is it possible do it only with strings?
I had a task that the user himself passes the data filters in the form of strings and I must save its structure, but give only those fields that are in the filters.
With existing functionality i don't know how to do it.
I create own two functions, which passed all my tests and helps me to do my task

**Comment by kurtbrose** [comment]
oh sorry, I think if you want to be able to do it with just strings, `'foo.*.bar'` is the only way

that's the next thing after our current release but I don't know exactly how fast things will go

**Comment by Niccolum** [comment]
If you have issue about this - just add link here and close this ticket. If not - can you add this issue to future features list?

**Comment by kurtbrose** [comment]
https://github.com/mahmoud/glom/pull/144
