### ISSUE TITLE
Pipe() -- Auto(tuple) for other modes

### ISSUE THREAD

**Issue by kurtbrose** [mahmoud/glom#167]
the behavior of tuple is Auto mode is especially useful (execute specs one after the other)

consider Pipe as an explicit version of this behavior

(`Pipe` chosen because it is very short and sounds like "attach end-to-end"; other options: `Chain`, `Pipeline`, ` Series`, `Line`, `Tuple`)

This is probably pretty uncontroversial

**Comment by mahmoud** [comment]
Yeah, Pipe's a fine name for this when we end up needing it.

**Comment by kurtbrose** [comment]
![image](https://user-images.githubusercontent.com/543934/89459969-631c2100-d71e-11ea-81ec-2912247c1470.png)
pops up a lot with match mode -- having to flip back and forth

**Comment by kurtbrose** [comment]
this is in
