### ISSUE TITLE
defining "paralanguage"?

### ISSUE THREAD

**Issue by kurtbrose** [mahmoud/glom#169]
do we like the term "paralanguage" for what glom is?

should we try to define it?  should we look for other terms?

glom is doing some things like a language -- stack traces, variable scopes -- but is still very much a native python library, not merely implemented in python

**Comment by mahmoud** [comment]
When it comes to the PL jargon, so far I've been describing glom as a DSL for data transformation, as well as a sublanguage with a single host language, Python. (I've also described it as an executable AST for nested data, but that doesn't really apply.)

In a way, all these names, including paralanguage, imply there's stuff glom can't do. Correct, if perhaps harmfully vague. To me, paralanguage is strongest in this connotation. "DSL" is probably the most widely known, less likely to raise suspicions.
