### ISSUE TITLE
set literal spec to build set result from iterable

### ISSUE THREAD

**Issue by kurtbrose** [mahmoud/glom#17]
`{T}` could work exactly like `[T]` but build up a set rather than a list

**Comment by mahmoud** [comment]
I've been mulling this for a bit and here are the reasons I'm against it:

1. Invalidates the useful side effect of basic glom usage being JSON serializable. (sets are not json-friendly)
2. Pretty trivial to implement with a chain to the set constructor.
3. Overly convenient. That is, its convenience is not commensurate with use. Once we get that extension API we can look at having a `Set()` spec _maybe_. (I'm pretty sold on always just chaining).

Good brainstorm, keep em coming, but I'm closing this one for now.
