### ISSUE TITLE
don't treat classes with glomit() methods as specs -- only instances

### ISSUE THREAD

**Issue by kurtbrose** [mahmoud/glom#184]
![image](https://user-images.githubusercontent.com/543934/89458691-48e14380-d71c-11ea-9a32-7d9dea93c4f7.png)

in `_glom()` ^

this would allow Match based meta-glom to refer to spec types directly instead of `lambda t: isinstance(t, SpecType)`

**Comment by kurtbrose** [comment]
oh whoops I guess the alternative is really `Check(type=SpecType)`

**Comment by mahmoud** [comment]
So really limit it down to bound methods? Ignore callable attributes and class/static methods? I guess that follows Python builtin operator overloading / data model stuff.

**Comment by kurtbrose** [comment]
whoops didn't mean to say disallow those others -- more if it is an unbound
method that is obviously gonna instantly fail

the goal is just to make spec types work in match for meta glom :-)
