### ISSUE TITLE
Coalesce + T usage

### ISSUE THREAD

**Issue by tshelburne** [mahmoud/glom#19]
I'm mapping a large dictionary to a smaller (but still with many properties) one using glom, and ran into a strange issue. I'm using `Coalesce` to easily enable a default for every property in the mapped values, and `T` to ease legibility of my code. I'm not sure if I'm missing something here and using it incorrectly, or if this is a difference which shouldn't happen. It basically looks like in the context of `Coalesce`, `T` works differently than a simple string path.

Simplified version:

```python
from glom import glom, T, Coalesce

complete_data = {
    'object': {
        'prop1': 1,
        'prop2': {
            'nested': 2,
        },
    },
}

limited_data = {
    'object': {
        'prop1': 1,
        'prop2': None,
    },
}

def full_coalesce(obj_spec):
    return {k: Coalesce(v, default=None) for k, v in obj_spec.items()}

obj = T['object']

working_spec = full_coalesce({
    'prop1': obj['prop1'],
    'nested': 'object.prop2.nested',  
})

broken_spec = full_coalesce({
    'prop1': obj['prop1'],
    'nested': obj['prop2']['nested'],
})

print glom(complete_data, working_spec)
print glom(limited_data, working_spec)
print glom(complete_data, broken_spec)
print glom(limited_data, broken_spec)
```

The output:

```shell
{'prop1': 1, 'nested': 2}
{'prop1': 1, 'nested': None}
{'prop1': 1, 'nested': 2}
Traceback (most recent call last):
  File "testing-glom.py", line 41, in <module>
    print glom(limited_data, broken_spec)
  File "./venv/lib/python2.7/site-packages/glom/core.py", line 919, in glom
    ret = self._glom(target, spec, path=path, inspector=inspector)
  File "./venv/lib/python2.7/site-packages/glom/core.py", line 949, in _glom
    val = self._glom(target, subspec, path=path, inspector=next_inspector)
  File "./venv/lib/python2.7/site-packages/glom/core.py", line 994, in _glom
    ret = self._glom(target, subspec, path=path, inspector=next_inspector)
  File "./venv/lib/python2.7/site-packages/glom/core.py", line 978, in _glom
    ret = _t_eval(spec, target, path, inspector, self._glom)
  File "./venv/lib/python2.7/site-packages/glom/core.py", line 678, in _t_eval
    cur = cur[arg]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by kurtbrose** [comment]
thanks!  I think this is a total bug -- the intention in `_t_eval` is to catch things that go wrong and re-raise them as "equivalent" GlomErrors, so that Coalesce &etc will interact nicely with them.

https://github.com/mahmoud/glom/blob/master/glom/core.py#L676-L683


```python
        elif op == '[':
            try:
                cur = cur[arg]
            except KeyError as e:
                path = _path_fmt(t_path[:i+2])
                raise GlomKeyError(path)
            except IndexError:
                raise GlomIndexError(_path_fmt(t_path[:i+2]))
```

need another check in there for TypeError!  Thanks!

**Comment by kurtbrose** [comment]
when you have a chance, would you mind installing from the master branch here and giving this a try?

(I think this issue is fixed with:
https://github.com/mahmoud/glom/commit/b2316b63a0aab4152ed52102b69f1902a6185d37)

will circle back around and add unit tests later but want to unblock you ASAP

**Comment by tshelburne** [comment]
Hi @kurtbrose, thanks so much for the quick addressing of the problem! I'll test this out shortly, we're in the middle of trying to launch, so it might be a minute before I can try it out.

**Comment by kurtbrose** [comment]
closing this issue for now -- we've had a release since the fix and hopefully no news is good news :-)
