### ISSUE TITLE
Beginner question for docs: Can "T" do filters and/or grouping? 

### ISSUE THREAD

**Issue by mborus** [mahmoud/glom#20]
Hi,

sorry if this is too obvious, but from the tutorial I can't understand if glom supports grouping or if this is not something it's intended to do.

If you extend the planets example to include a category and sum up the moons by that category?

    from glom import glom, T
    target = {'system': {'planets': [{'name': 'earth', 'category':1, 'moons': 1},
        {'name': 'pluto', 'category':1, 'moons': 5},
        {'name': 'uranus', 'category':2, 'moons': 5},
        {'name': 'jupiter', 'category':2, 'moons': 69}]}}

    spec = T['system']['planets']

if I wanted to sum up the moons by category, I could run

    [
        sum([p['moons'] for p in glom(target, spec) if p['category'] == 1]),
        sum([p['moons'] for p in glom(target, spec) if p['category'] == 2])
    ]

But is there a way of adding filtering (for example sum only category 2) or grouping directly to the spec?

Of is this outside the scope of glom?

##UPDATE##

    A spec without the T notation works for filtering:

    spec = ('system.planets', [lambda x : x['moons'] if x['category'] == 2 else OMIT], sum)

    As the T-notation is not fixed yet, I'm closing the issue.

**Comment by mahmoud** [comment]
Hey @mborus I just saw the update, and yes, `OMIT` + chaining (tuples) with functions (like `sum` in your example above) is exactly the pattern I use to achieve basic filtration + grouping. Definitely taking PRs for the snippets page, where we try to collect such patterns; http://glom.readthedocs.io/en/latest/snippets.html :)
