### ISSUE TITLE
Is there a way to merge two list based on their dict's key by glom?

### ISSUE THREAD

**Issue by neocxf** [mahmoud/glom#205]
First, thanks for your awesome project.

Let's say we have two different list of dicts:
**list1**
`
[{'id': 1, 'username': 'jack'}, {'id': 2, 'username': 'john'}]
`
**list2**
`
[{'id': 1, 'username': 'tom'}, {'id': 3, 'username': 'kate'}]
`

I want to merge the two different list by `id`, and the later list take precedence. The final desired list will be:
**list3**
`
[{'id': 1, 'username': 'tom'}, {'id': 2, 'username': 'john'},{'id': 3, 'username': 'kate'}]
`

Can I use glom to achieve this? I have already read the docs of the official or any solutions on stackoverflow. But still without 
any idea. Thanks in advance

**Comment by mborus** [comment]
Yes,

If you add the lists together like

    mylist = [{'id': 1, 'username': 'jack'}, {'id': 2, 'username': 'john'}] + [{'id': 1, 'username': 'tom'}, {'id': 3, 'username': 'kate'}]

you can use this spec

    from glom import glom, T, Iter, Merge
    spec = Iter({T['id']: T}), Merge(), T.values(), list

where

    print(glom(mylist, spec))

will result in

     [{'id': 1, 'username': 'tom'}, {'id': 2, 'username': 'john'}, {'id': 3, 'username': 'kate'}]

BTW, make sure to ask these kind of questions on stackoverflow and mark them with the `glom` tag for others to find them more easily.
