### ISSUE TITLE
PathAccessError for value key with dot

### ISSUE THREAD

**Issue by samir86TIIR** [mahmoud/glom#230]
Hello,

It's not possible to use dot [.] on a value key with glom, 
For exemple:

`target = {
    'galaxy': {
        'solar.system': {
            'planet' : 'jupiter'
        }
    }
}
spec = 'galaxy.solar.system.planet'
glom(target, spec)`

We have this error, because the value **'solar.system'** isn't recognize :

![issue_glom](https://user-images.githubusercontent.com/57186223/142419588-15d66b44-cb19-4225-b841-0c47715328c2.JPG)

Any help will be greatly appreciated because it's very painful to modify a JSON file with a lot dotted keys.

**Comment by mahmoud** [comment]
Hey there Samir! Check out the Path spec type: https://glom.readthedocs.io/en/latest/api.html#glom.Path

**Comment by samir86TIIR** [comment]
Hi Mahmoud,
It's working great, thank you for your reactivity, 
I'm a beginner glom user, and I will read more deeply glom functions :)
