### ISSUE TITLE
Should we use this or boltons.remap?

### ISSUE THREAD

**Issue by matanster** [mahmoud/glom#237]
Thanks for this great library. Just a question, how should one position this v.s. https://sedimental.org/remap.html when choosing api for data manipulation? they may seem to have some overlap on first look.

**Comment by majidaldo** [comment]
bump. same question.

**Comment by mahmoud** [comment]
Oh, great question! So my standard recommendation on this: 

* If you know the shape of the output ahead of time, then glom is what you want.
* If your output shape is determined by the input, then remap is the way to go.

Remap performs a full traversal of a nested data structure, walking it like a tree. In contrast, glom only goes where it's told by the spec.

We've still got our eye on integrating remap-like features, but we haven't found an API we liked yet.

Does that make sense? I'd like to get a good answer to put in the FAQ doc :)

**Comment by mahmoud** [comment]
For example:

You run an error reporting service. Users send you an arbitrary dictionary of metadata related to the error. But you have a requirement that you don't store secrets. 

Remap is a great way to traverse that full structure, look for all keys containing the substring "secret" and replacing the value with "[REDACTED]". The output shape will be the same as the input shape.

Glom doesn't have a way to do that now. The output shape is predefined by the spec.

**Comment by majidaldo** [comment]
I feel like glom could be built ontop of remap; b/c remap is more general but glom is more specific. The glom specs are like the remap queries and visitors.

**Comment by mahmoud** [comment]
That'd be a fun challenge! But for day-to-day usage, it's rarely necessary to visit every element of a target structure. And design-wise remap's hooks don't have as much context as glom's plugin architecture. There's a reason we built (and [still use](https://gist.github.com/mahmoud/9a1f25b563e9e95f58241e74f864e65c)!) remap, and then built glom :)

**Comment by mahmoud** [comment]
Great! I added a FAQ entry here: https://glom.readthedocs.io/en/latest/faq.html#should-i-use-glom-or-remap
