### ISSUE TITLE
GitHub releases not updated for 23.1.0 and 23.1.1

### ISSUE THREAD

**Issue by maovidal** [mahmoud/glom#256]
Hi!
Quick question: I just noted that the 23.1.0 and 23.1.1 releases have not been included at https://github.com/mahmoud/glom/tags then GitHub hasn't provided notifications of these releases.
Is there any particular reason for that?
BTW, thank you for this app. It is a neat and I love it.

**Comment by mahmoud** [comment]
Hey Mauricio! Not a good reason: fresh OS install, forgot to turn on tag pushing by default. Tags are pushed now. Thanks for the heads up!

**Comment by maovidal** [comment]
Hi Mahmoud!
Just to let you know that it seems the issue persists as the 23.3.0 release was not included on the tags.
