### ISSUE TITLE
`skip` option for Coalesce doesn't seems to work

### ISSUE THREAD

**Issue by antoine-gallix** [mahmoud/glom#266]
Below a snippet of code where I convert variables to float. I want to skip trying to convert empty strings and have the default value instead. But I can't seem to make the `skip` option work.

```python
from glom import Coalesce, glom
glom( [1, "1", ""], [Coalesce(float, default=None, skip="")])

# GlomError.wrap(ValueError): error raised while processing, details below.
#  Target-spec trace (most recent last):
#  - Target: [1, '1', '']
#  - Spec: [Coalesce(float, default=None, skip='')]
#  - Target: ''
#  - Spec: Coalesce(float, default=None, skip='')
#  - Spec: float
#            ^^^^^^^^^^^^
# ValueError: could not convert string to float: ''
```

My expected result would be `[1, 1, None]`

Am I understanding something wrong with how to use `skip`? The documentation is unclear.

**Comment by antoine-gallix** [comment]
I get the same error with `skip=("",)` and `skip=lambda v:v==""`

**Comment by mahmoud** [comment]
Hey @antoine-gallix! So `skip` is actually checked against the value _after_ evaluating the spec passed to `Coalesce` (`float`, in this case). Depending on your use case, you might want to do `skip_exc=ValueError` to skip un-`float`-ables. Hope this helps!
