### ISSUE TITLE
replicate logic with Switch

### ISSUE THREAD

**Issue by antoine-gallix** [mahmoud/glom#268]
I've tried many forms of spec, but I haven't been able, just by reading the documentation of `Switch`, to replicate the following logic with it:

```python
def spec(target):
    if target.get("condition", False):
        return target.get("this", None)
    else:
        return target.get("that", None)


data = {"condition": True, "this": "A", "that": "B"}
# spec(data) => 'A'
data = {"condition": True, "that": "B"}
# spec(data) => None
data = {"condition": False, "this": "A", "that": "B"}
# spec(data) => 'B'
data = {"condition": False, "this": "A"}
# spec(data) => None
data = {'this': 'A', 'that': 'B'}
# spec(data) => B
data = {'this': 'A'}
# spec(data) => None
```

What's the solution?

**Comment by kurtbrose** [comment]
Here's one approach:

```python
spec = Switch({T.get("condition"): T.get("this")}, default=T.get("that"))
```

Another way to go about it is use something that will always be True to make a default inside the Switch dict:

```python
spec = Switch({T.get("condition"): T.get("this"), Val(True): T.get("that")})
```

You can also use `glom.And` / `glom.Or` to achieve what you want through short-circuit logic:

```python
And("condition", T.get("this"), default=T.get("that"))
Or(And("condition", T.get("this")), T.get("that"))
```

This expression looks most concise to me: `And("condition", T.get("this"), default=T.get("that"))` -- although it is also 100% valid to embed that `spec()` function you wrote inside a spec.

Whatever is most readable!

**Comment by antoine-gallix** [comment]
Thanks!
