### ISSUE TITLE
Missing assert in test_mutation.py

### ISSUE THREAD

**Issue by Sjord** [mahmoud/glom#269]
[glom/glom/test/test\_mutation.py at master · mahmoud/glom](https://github.com/mahmoud/glom/blob/master/glom/test/test_mutation.py#L208)

```
def test_s_assign():
    '''
    check that assign works when storing things into S
    '''
    glom({}, (Assign(S['foo'], 'bar'), S['foo'])) == 'bar'
```

`glom(...) == 'bar'` should probably be  `assert glom(...) == 'bar'`

**Comment by mahmoud** [comment]
Great catch, both here and #270. Now I'm wondering if there's a pytest plugin to warn when a test function doesn't perform a single assert :) Thanks!
