### ISSUE TITLE
Enumerate and Assign

### ISSUE THREAD

**Issue by boonhapus** [mahmoud/glom#272]
I'm ingesting data from an API that I want to enumerate, and assign that enumeration to an `ID` field. You can imagine that the `data` is sometimes in the order I want, and sometimes I am required to order it myself -- essentially what's below is a MVE, but the concept is still the same.

```python
>>> from glom import glom, T, A, S, Assign
>>>
>>> data = [
...     {"letter": "a"},
...     {"letter": "b"},
...     {"letter": "c"},
... ]
>>>
>>> spec = (
...     enumerate,
...     [
...         (
...             Assign(T[1]["id"], T[0]),
...             T[1]
...         )
...     ]
... )
>>>
>>> glom(data, spec)
[
    {"letter": "a", "id": 0},
    {"letter": "b", "id": 1},
    {"letter": "c", "id": 2}
]
```

While I've got this working, it's feels really terse and I'm curious if there's a better way here.

**Comment by boonhapus** [comment]
This spec seems WAY more readable. 😃 I found the example from **[this old issue](https://github.com/mahmoud/glom/issues/115#issuecomment-548965256)**, totally didn't think of simply calling `dict` on the existing mapping, which is totally what I want.

```python
spec = (
    enumerate,
    [Invoke(dict).specs(T[1], id=T[0])]
)
```

**Comment by mahmoud** [comment]
Awesome! Thanks for checking past issues. I sometimes mine those for tips, too. If this sort of thing comes up often enough, maybe we can make it a snippet? https://glom.readthedocs.io/en/latest/snippets.html
