### ISSUE TITLE
python-full isn't an accepted spec format

### ISSUE THREAD

**Issue by catlee** [mahmoud/glom#34]
The CLI help specifies that 'python-full' is an acceptable option for the spec format, but if you try and use it, you get an error: `expected spec-format to be one of python or json`

**Comment by mahmoud** [comment]
Hey Chris! Yeah, that feature's a-comin. I may see if I can knock a quick version out tonight. I'd say expect it in glom 18.2.0, sometime in the next couple weeks :)

If you don't mind me asking, can you share your use case? Part of the reason I haven't got around to it is that my command-line gloms have always been on the short-and-simple side.

**Comment by catlee** [comment]
I'm not sure if I had a valid usecase or not. This was my first time using glom, and I was trying to figure out a way to list the keys of a dictionary in a large json file.

I guessed that maybe the 'python-full' spec format would allow me to use the `T` object, and that something like `glom --spec-format python-full "T.keys()"` might work, but was ultimately unsuccessful figuring out the right spec to use.
