### ISSUE TITLE
glom equivalent for assignment to nested data structures?

### ISSUE THREAD

**Issue by borenstein** [mahmoud/glom#38]
First of all, this is a wonderful package, and basically ideal for my [core use case](https://medium.com/@open990/the-irs-990-e-file-dataset-getting-to-the-chocolatey-center-of-data-deliciousness-90f66097a600). 

When writing tests for glommy kinds of stuff, I sometimes have to go the other way: assigning something to some deeply nested data structure:

    my_obj["a"]["b"]["c"]["d"] = True

Right now, all my ways of handling this are kind of cloodgy. But it seems like there could be an inverse glom that could do something like this:

    iglom(my_obj, "a.b.c.d", True)

Realistic? Is there something that already does this? I bet there's something that already does this and I missed the memo.

**Comment by kurtbrose** [comment]
we hear you!  :-)

`Assign` glom has been bumped up in priority based on demand / use cases; will merge soon: https://github.com/mahmoud/glom/pull/44

**Comment by mahmoud** [comment]
Good news, @borenstein! With the glom 18.3.0 release, we now have an `assign()` function, as well as a spec type (for performing multiple assignments in the same glom call, among other things). Docs here:

https://glom.readthedocs.io/en/latest/api.html#target-mutation-with-assign

Give it a whirl, and let us know how you like it! Thanks again for the request!
