### ISSUE TITLE
Correction to Snippet "Filter Iterable"

### ISSUE THREAD

**Issue by SegundoBob** [mahmoud/glom#53]
The snippet [Filter Iterable](https://glom.readthedocs.io/en/latest/snippets.html#filter-iterable)
```
glom(['cat', 1, 'dog', 2], Check(types=str, default=OMIT))
```
Gives me results:
```
Sentinel('OMIT')
```
Adding a pair of brackets gives me the expected result.
```
glom(['cat', 1, 'dog', 2], [Check(types=str, default=OMIT)])
```
Result:
```
['cat', 'dog']
```

**Comment by mahmoud** [comment]
Good eye, thanks very much!

**Comment by SegundoBob** [comment]
My pleasure.  glom is very useful.
