### ISSUE TITLE
more googleable T and S?

### ISSUE THREAD

**Issue by kurtbrose** [mahmoud/glom#58]
T and S are really hard to google for -- see Q and F in django queries;

in the documentation verbiage refer to "T" as "TARGET" and "S" as "SCOPE", then in all code samples we can use T and S, and advise users to do so, but if you google for "what is TARGET glom" they will get meaningful hits in our docs

**Comment by mahmoud** [comment]
Hmm, searches of "acme" and "ACME" on google seem to indicate that it's not actually that case sensitive, so normal "target" and "scope" refs will show up in your proposed scheme.

"T object" and "S object" is how I think of them, and `"T object" glom` [gives some decent SEO](https://www.google.com/search?channel=fs&q=%22t+object%22+glom&ie=utf-8&oe=utf-8). Good enough, eh?
