### ISSUE TITLE
Overload an operator to invoke glom

### ISSUE THREAD

**Issue by scizzorz** [mahmoud/glom#61]
I've been using glom a fair amount lately, but one thing that's mildly frustrating is how obvious it is that I'm using it:

```
a = data['owner']['name']['last']
b = glom(data, T['owner']['name']['last'])
```

Personally, I think the second assignment is a bit more convoluted and hard to read at  a glance. However, if there was some sort of operator overload on `T`, I think it could be a lot cleaner:

```
c = data | T['owner']['name']['last']
```

Looking at the definition of `TType`, it seems like adding an operator overload would be pretty simple. In this case, it would be the `__ror__` operator.

Another idea that I think might clean things up a bit is a wrapper that facilitates something like this:

```
d = G(data)['owner']['name']['last']
```

But I'm not sure how you would "conclude" the lookup and tell it to evaluate, rather than keep providing a nestable object.

**Comment by kurtbrose** [comment]
are you using it just for deep-gets?  maybe there's a helper possible for that use case -- the only thing I'm nervous about is `glom(2, 3 | T)` might be ambiguous -- if it is being used as "evaluate immediately" operator, that will reduce to `glom(2, 3)` which will return `3` -- if it is being used as "T is a stand-in for the target" then this will reduce to `3 | 2` which will return `7`

if we have a separate global specifically for this purpose e.g.` G` or `GET` then this is a non-issue -- we can disallow G or GET as part of a glom-spec, their only purpose is as a deep-get helper

some more context --

the T object kind of arose out of earlier discussions:

https://github.com/mahmoud/boltons/issues/147

I've seen | proposed as a kind of chaining mechanism for single-arg functions before (a la https://gist.github.com/miyuchina/f463bbd8ad605d8c9a56aef83709ebe2)

**Comment by scizzorz** [comment]
As it stands, `T` doesn't overload anything except `__getattr__`,  `__getitem__`, and `__call__`, so I was assuming that "T is a stand-in for the target" wasn't a design goal. That leaves it to the former case: `3 | T` evaluates immediately to `3`.

I've also seen `|` proposed as that chaining mechanism - it's somewhat similar to Unix pipes, I suppose. It becomes too much of a hassle to manually monkey patch every function to work with it, though.
