### ISSUE TITLE
true "empty" path (P?)

### ISSUE THREAD

**Issue by kurtbrose** [mahmoud/glom#70]
T = target, S = scope
P = path?
P is the 0 of path operations?

```Path(T, P, P, P, P) == Path(T)```

currently there are a few places we assume T is the "blank" path; this paints us into a corner when we want to break a path into chunks as in assign when we break the "GOTO" prefix from the "ASSIGN THIS VALUE" tail of the path

maybe we should have a true "empty" path global, and T and S should be like different root directories

P for Path?

R for Relative?

**Comment by mahmoud** [comment]
I think we pretty much solved this in #71, with `T` playing this role in almost all cases. Closing for now.
