### ISSUE TITLE
Allow deep apply function

### ISSUE THREAD

**Issue by antoine-gallix** [mahmoud/glom#73]
The Assign is a great enhancement of glom features. But it seems to work only with fixed values, whereas the fetch syntax allows execution of function at a given path. The most simple example would be:
```python
from glom import assign,Call,T

o = {'a': 2}

def f(x):
    return 2 * x

# classic python
o['a'] = f(o['a'])
# > {'a': 4}

assign(o, 'a', f) # doesn't work
# > {'a': <function f at 0x7effe21b91e0>}

assign(o, 'a', Call(f)) # doesn't work
# > Call(<function f at 0x7f65c8c7a1e0>, args=(), kwargs={})

assign(o, 'a', f(T['a']))
# TypeError: unsupported operand type(s) for *: 'int' and 'TType'

```
A more realistic use case would be:

```python
from functools import partial
from operator import itemgetter

sort_by_quantity = partial(sorted,key=itemgetter('quantity'))
assign(fat_nested_structure,'long.path.to.a.list.of.dicts',sort_by_quantity)
# expected fat_nested_structure["long"]["path"]["to"]["a"]["list"]["of"]["dicts"] get sorted inplace by 'quantity'
```

**Comment by mahmoud** [comment]
Hey Antoine, glad you like Assign! It's kind of a niche thing, so it's very gratifying to see it get some use.

Assign [will actually evaluate any Spec for the value](https://glom.readthedocs.io/en/latest/api.html#glom.Assign), but only if it's explicitly wrapped as a [Spec](https://glom.readthedocs.io/en/latest/api.html#glom.Spec).

I agree that the Call not working is too tricky, I'll think on opening that up. For now, wrap it in a Spec and you should be good!

```python
>>> x = {}
>>> glom.assign(x, 'hi', lambda x: 'Hallo')
{'hi': <function <lambda> at 0x7fba623586e0>}   # not what you want
>>> glom.assign(x, 'hi', glom.Spec(lambda x: 'Hallo'))
{'hi': 'Hallo'}   # seems to work ok!
```

**Comment by antoine-gallix** [comment]
Oh, thank you that's great! It doesn't seems a niche thing to me, that feature is really powerfull. It allows to write functional code easily:

```python
from functools import partial
from operator import itemgetter
from glom import Assign,glom,Spec

sort_by_quantity = partial(sorted,key=itemgetter('quantity'))
deep_path='long.path.to.a.list.of.dicts'
sort_deep_list=Assign(deep_path,Spec((deep_path,sort_by_quantity)))

# reusable deep sort
glom(fat_nested_structure,sort_deep)
```

**Comment by antoine-gallix** [comment]
Made a PR for the doc: https://github.com/mahmoud/glom/pull/74
