### ISSUE TITLE
Extract tuples from complex objects?

### ISSUE THREAD

**Issue by antoine-gallix** [mahmoud/glom#77]
Is there a spec that can do the following ?

```python
d = {'a': 1, 'b': 2}
glom(d, <some_spec_here>)
>> (1,2)
```

My intended use case is to extract tuples of selected data from complex items, that could be then used for sorting or grouping. Glom API creates easily dict outputs, but in the case the output needs to be an immutable tuple. It also differs from the nested list example of the tutorial because each element of the tuple is reached through a different path.

**Comment by mahmoud** [comment]
For more powerful extractions, you can use the `T` specifier type to get exactly what you need. For this particular case I would do:

```
>>> from glom import glom, T
>>> d = {'a': 1, 'b': 2}
>>> glom(d, (T.items(), sorted, tuple))
(1, 2)
```

[Read more about T here.](https://glom.readthedocs.io/en/latest/api.html#object-oriented-access-and-method-calls-with-t) :)

**Comment by antoine-gallix** [comment]
Thank you! (Sorry, I forgot to close the issue)

**Comment by mahmoud** [comment]
No worries! We're actually sketching out an explicit tuple builder, too. Keep an eye on the changelog! :)
