### ISSUE TITLE
Is there a way to cast list to the dict?

### ISSUE THREAD

**Issue by proofit404** [mahmoud/glom#85]
Hi, thanks for the awesome project!

Is there a way to convert `[{"id": 1, "name": "foo"}, {"id": 2, "name": "bar"}]` to `{1: "foo", 2: "bar"}`?

Best regards, Artem.

**Comment by mahmoud** [comment]
There sure is! As of glom 19.2.0 you can now do:

```python
from glom import glom, T, Merge

target = [{"id": 1, "name": "foo"}, {"id": 2, "name": "bar"}]
spec = Merge([{T["id"]: T["name"]}])

glom(target, spec)
# {1: 'foo', 2: 'bar'}
```

The new changes are not only the `Merge()` spec, but also the ability to set keys using [`T`](https://glom.readthedocs.io/en/latest/api.html#object-oriented-access-and-method-calls-with-t) (and Spec objects).

By the way, if it's not too much trouble: if you have a StackOverflow, could you duplicate your question over there? I'll certainly upvote, but mostly I suspect it's more discoverable for more users :)

Thanks in advance!

**Comment by proofit404** [comment]
https://stackoverflow.com/questions/54762136/is-there-a-way-to-merge-a-list-of-dicts-into-a-single-dict-using-glom-library

Sorry, it taked too long.

**Comment by mahmoud** [comment]
Haha, someone beat me to it! You should accept their answer, with my thanks!
