### ISSUE TITLE
Having a default/fallback for a specific missing path

### ISSUE THREAD

**Issue by liiight** [mahmoud/glom#87]
I have the following data structure:
```python
from glom import glom

bar = [{'foo': 'bar'}, {}, {'foo': 'baz'}]
spec = ['foo']
print(glom(bar, spec))
```
This fails with a path error:
```
Traceback (most recent call last):
  File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/glom/core.py", line 888, in _t_eval
    cur = get(cur, arg)
KeyError: 'foo'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/glom/core.py", line 1448, in glom
    ret = _glom(target, spec, scope)
  File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/glom/core.py", line 1468, in _glom
    return _handle_list(target, spec, scope)
  File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/glom/core.py", line 1172, in _handle_list
    val = scope[glom](t, subspec, scope.new_child({Path: scope[Path] + [i]}))
  File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/glom/core.py", line 1472, in _glom
    return Path.from_text(spec).glomit(target, scope)
  File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/glom/core.py", line 306, in glomit
    return _t_eval(target, self.path_t, scope)
  File "/Users/orcarmi/PycharmProjects/shield/venv/lib/python3.6/site-packages/glom/core.py", line 890, in _t_eval
    raise PathAccessError(e, Path(_t), i // 2)
glom.core.PathAccessError: could not access 'foo', part 0 of Path('foo'), got error: KeyError('foo',)
```
I'd like to be able to overcome the missing element in the data structure without needing to sanitize the data. 

Is that possible?
using glom 19.2.0, python 3.6

Thanks!

**Comment by liiight** [comment]
Was able to solve it with SKIP:

```python
bar = [{'foo': 'bar'}, {}, {'foo': 'baz'}]
spec = [lambda t: t['foo'] if t.get('foo') else SKIP]
print(glom(bar, spec))

['bar', 'baz']
```
Sorry for the noise and thanks for this amazing lib!

**Comment by mahmoud** [comment]
Hey Or! Glad you got it solved. Glom's pretty flexible, so there's more than one way to do things. I was going to recommend trying [Coalesce](https://glom.readthedocs.io/en/latest/api.html#conditional-access-and-defaults-with-coalesce).

```
from glom import glom, SKIP, Coalesce

bar = [{'foo': 'bar'}, {}, {'foo': 'baz'}]
spec = [Coalesce('foo', default=SKIP)]

print(glom(bar, spec))
['bar', 'baz']
```

You can also use a different default, or specify fallback specs, for more advanced cases than the good ole foo/bar. Good luck!

**Comment by liiight** [comment]
Thanks, Coalesce is definitely more elegant!

This is not related to the topic at hand, and if that's not ok then I apologize, but I wonder if there is an option to use wildcards.

I have the following schema:
```python
foo = [{'string': 'bar'}, {'integer': 1}, {'float': 0.5}]
```
I'm not sure which spec I should use to get:
```python
['bar', 1, 0.5]
```
Is that possible? 
Thanks in advance

**Comment by mahmoud** [comment]
I just wish it was happening on StackOverflow so I could get some pointsssss! :package: 

Depends what you mean here. If you want only one from each, and a specific set of keys, you could do:

```
from glom import glom, SKIP, Coalesce

foo = [{'string': 'bar'}, {'integer': 1}, {'float': 0.5}]
spec = [Coalesce('string', 'integer', 'float', default=SKIP)]

print(glom(foo, spec))
['bar', 1, 0.5]
```

if you want all the values, ignoring the keys:

```
from glom import glom, Flatten, T

foo = [{'string': 'bar'}, {'integer': 1}, {'float': 0.5}]
spec = Flatten([T.values()])

print(glom(foo, spec))
['bar', 1, 0.5]
```

Hope that helps!

**Comment by liiight** [comment]
@mahmoud thanks a lot, that helps a lot!

glom is super cool and powerful, but I have to say it has a bit of a learning curve. With you example I now feel like I have a much better understanding of both Coalesce and T, so thanks again!
