### ISSUE TITLE
How to add a key to a target dict in single spec

### ISSUE THREAD

**Issue by lukeshao** [mahmoud/glom#93]
Hi, I need change some scripts from pyjq to glom. The target is to get the data dict and add the id key to it. 

E.g. input:
```python
{
  'name': 'abc'
  'data': {
    'a': '1',
    'b': '2'
  },
  'id': '123'
}
```
Output :
```python
{
  'data': {
    'a': '1',
    'b': '2',
    'id': '123'
  }
}
```

In pyjq, we can have something like: "data: (.data + {id: .id})".  Is it possible to implement it in a single glom spec? Thanks in advance!

**Comment by svanburen** [comment]
not in a single spec, but you could combine `glom.assign` and `glom.glom`:

```python
∆ target = {
..  'name': 'abc',
..  'data': {
..    'a': '1',
..    'b': '2'
..  },
..  'id': '123'
..}

∆ x = glom.assign(target, 'data.id', glom.glom(target, 'id'))["data"]

∆ x
Out[10]: {'a': '1', 'b': '2', 'id': '123'}
```

**Comment by mahmoud** [comment]
Hi @lukeshao! Great question. @svanburen's solution is pretty close to the one I would use, so hopefully you're not blocked :)

Relative specs are still being developed inside glom, but that would make this case trivial, so thank you for bringing it up. Helps prioritize :)

If you **MUST** do it in a single spec, you can use this:

```python
import glom 
import glom

target = {'name': 'abc',
          'data': {
              'a': '1',
              'b': '2'
          },
          'id': '123'
}

spec = ({'data': ('data', dict)},  # copy the data dict before we assign
        glom.Assign('data.id', glom.Spec(glom.S['id'])))

output = glom.glom(target, spec, scope=target)
```

Note that you must pass in target as the `scope` arg as well, to make the `S` reference work.

But yeah, another good use case for relative paths :)

**Comment by lukeshao** [comment]
@mahmoud it works for me. Thanks!

@svanburen thanks for the answer!
