### ISSUE TITLE
How to set defaults not globally

### ISSUE THREAD

**Issue by berend** [mahmoud/glom#98]
I want to use `glom` to transform a dictionary according to a spec. Sometimes there are some objects not set ( = `None`), which I want to default to a value. I found out, how to do this globally with `glom`, but I struggle with "local" or specific defaults.

My example:
```python
data = {
    "item": {"id": 1337},
    "budget": {"amount": 1234},
    "cost": None
}

spec = {
    "item_id": "item.id",
    "budget": "budget.amount",
    "cost": "cost.amount"
}

glom(data, spec, default=0)

```
gives me 
```
0
```
But I want 
```
{
    "item_id": 1337,
    "budget": 1234,
    "cost": 0
}
```

I tried to replace `"cost.amount"` from my spec (with `lambda`, nested glom), but failed. Can `glom` do this?

**Comment by kurtbrose** [comment]
This is exactly what Coalesce is for (sorry for the slow reply)

https://glom.readthedocs.io/en/latest/api.html#conditional-access-and-defaults-with-coalesce
